version: '2'
services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g
    # volumes:
    #     - ~/volumes/jhipster/<%= baseName %>/oracle/data:/u01/app/oracle
    environment:
      - DBCA_TOTAL_MEMORY=1024
      - WEB_CONSOLE=true
    ports:
      - 1580:8080
      - 1521:1521
